<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="modeling"
    nsURI="http://ns.storydriven.org/sdm/0.1.0" nsPrefix="sdm">
  <eClassifiers xsi:type="ecore:EClass" name="Expression" abstract="true" eSuperTypes="#//TypedElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="TypedElement" abstract="true" eSuperTypes="#//ExtendableElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" ordered="false" eType="ecore:EClass platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EClassifier"
        unsettable="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="genericType" ordered="false"
        eType="ecore:EClass platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EGenericType"
        unsettable="true" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ExtendableElement" abstract="true" eSuperTypes="platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EObject">
    <eOperations name="getExtension" ordered="false" lowerBound="1" eType="#//Extension">
      <eParameters name="type" ordered="false" lowerBound="1" eType="ecore:EClass platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EClass"/>
    </eOperations>
    <eOperations name="provideExtension" ordered="false" lowerBound="1" eType="#//Extension">
      <eParameters name="type" ordered="false" lowerBound="1" eType="ecore:EClass platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EClass"/>
    </eOperations>
    <eOperations name="getAnnotation" ordered="false" lowerBound="1" eType="ecore:EClass platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EAnnotation">
      <eParameters name="source" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eOperations name="provideAnnotation" ordered="false" lowerBound="1" eType="ecore:EClass platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EAnnotation">
      <eParameters name="source" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="annotation" ordered="false"
        upperBound="-1" eType="ecore:EClass platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EAnnotation"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="extension" ordered="false"
        upperBound="-1" eType="#//Extension" containment="true" eOpposite="#//Extension/extendableBase"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Extension" abstract="true" eSuperTypes="#//ExtendableElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="base" ordered="false" lowerBound="1"
        eType="ecore:EClass platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EObject"
        changeable="false" volatile="true" transient="true" derived="true">
      <eAnnotations source="union"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="modelBase" ordered="false"
        eType="ecore:EClass platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EModelElement"
        volatile="true" transient="true" unsettable="true" derived="true">
      <eAnnotations source="subsets" references="#//Extension/base"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="owningAnnotation" ordered="false"
        eType="ecore:EClass platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EAnnotation"
        volatile="true" transient="true" unsettable="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="extendableBase" ordered="false"
        eType="#//ExtendableElement" eOpposite="#//ExtendableElement/extension">
      <eAnnotations source="subsets" references="#//Extension/base"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StringExpression" eSuperTypes="#//Expression">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="expression" ordered="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="language" ordered="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NamedElement" abstract="true" eSuperTypes="#//ExtendableElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" ordered="false" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CommentableElement" abstract="true"
      eSuperTypes="#//ExtendableElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="comment" ordered="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eSubpackages name="expressions" nsURI="http://ns.storydriven.org/sdm/expressions/0.1.0"
      nsPrefix="sdme">
    <eClassifiers xsi:type="ecore:EClass" name="Collaboration" eSuperTypes="#//Expression">
      <eStructuralFeatures xsi:type="ecore:EReference" name="source" ordered="false"
          eType="#//pattern/Object" eOpposite="#//pattern/Object/sentCollaboration"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="target" ordered="false"
          upperBound="-1" eType="#//pattern/Object" eOpposite="#//pattern/Object/receivedCollaboration"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="body" ordered="false"
          eType="#//Expression" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="forEach" ordered="false"
          lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ComplexExpression" eSuperTypes="#//Expression">
      <eStructuralFeatures xsi:type="ecore:EReference" name="childExpression" lowerBound="1"
          upperBound="-1" eType="#//Expression" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ForLoop" eSuperTypes="#//Expression">
      <eStructuralFeatures xsi:type="ecore:EReference" name="loopVariable" ordered="false"
          lowerBound="1" eType="ecore:EClass platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EAttribute"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="startValue" ordered="false"
          lowerBound="1" eType="#//Expression" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="stopValue" ordered="false"
          lowerBound="1" eType="#//Expression" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="WhileLoop" eSuperTypes="#//Expression">
      <eStructuralFeatures xsi:type="ecore:EReference" name="loopCondition" ordered="false"
          eType="#//Expression" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="body" ordered="false"
          eType="#//Expression" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ConditionalExpression" eSuperTypes="#//Expression">
      <eStructuralFeatures xsi:type="ecore:EReference" name="condition" ordered="false"
          lowerBound="1" eType="#//Expression" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="then" ordered="false"
          eType="#//Expression" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="else" ordered="false"
          eType="#//Expression" containment="true"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="pattern" nsURI="http://ns.storydriven.org/sdm/pattern/0.1.0"
      nsPrefix="sdmp">
    <eClassifiers xsi:type="ecore:EClass" name="AttributeExpression" eSuperTypes="#//NamedElement">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="operator" ordered="false"
          lowerBound="1" eType="#//pattern/Operator" defaultValueLiteral="EQUAL"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="owningObject" ordered="false"
          lowerBound="1" eType="#//pattern/Object" eOpposite="#//pattern/Object/ownedAttributeExpression"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="attribute" ordered="false"
          lowerBound="1" eType="ecore:EClass platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EAttribute"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="value" ordered="false"
          upperBound="-1" eType="#//Expression" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="Operator">
      <eLiterals name="ASSIGN"/>
      <eLiterals name="EQUAL" value="1"/>
      <eLiterals name="NOT_EQUAL" value="2"/>
      <eLiterals name="LESS" value="3"/>
      <eLiterals name="GREATER" value="4"/>
      <eLiterals name="LESS_EQUAL" value="5"/>
      <eLiterals name="GREATER_EQUAL" value="6"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="BoundType">
      <eLiterals name="BOUND"/>
      <eLiterals name="UNBOUND" value="1"/>
      <eLiterals name="MAYBE_BOUND" value="2"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="Constraint">
      <eLiterals name="NONE"/>
      <eLiterals name="NEGATIVE" value="1"/>
      <eLiterals name="OPTIONAL" value="2"/>
      <eLiterals name="SET" value="3"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Link" eSuperTypes="#//NamedElement">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="constraint" ordered="false"
          lowerBound="1" eType="#//pattern/Constraint" defaultValueLiteral="NONE"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="modifier" ordered="false"
          lowerBound="1" eType="#//pattern/Modifier" defaultValueLiteral="NONE"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="target" ordered="false"
          lowerBound="1" eType="#//pattern/Object" eOpposite="#//pattern/Object/linkToSource"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="source" ordered="false"
          lowerBound="1" eType="#//pattern/Object" eOpposite="#//pattern/Object/linkToTarget"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="multiLinkToTarget" ordered="false"
          upperBound="-1" eType="#//pattern/MultiLink" eOpposite="#//pattern/MultiLink/targetLink"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="multiLinkFromSource"
          ordered="false" upperBound="-1" eType="#//pattern/MultiLink" containment="true"
          eOpposite="#//pattern/MultiLink/sourceLink"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="sourceEnd" ordered="false"
          eType="ecore:EClass platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EReference"
          volatile="true" transient="true" derived="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="targetEnd" ordered="false"
          eType="ecore:EClass platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EReference"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="rangeExpression" ordered="false"
          eType="#//Expression" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="Modifier">
      <eLiterals name="NONE"/>
      <eLiterals name="CREATE" value="1"/>
      <eLiterals name="DESTROY" value="2"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="MultiLink" eSuperTypes="#//ExtendableElement">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="index" ordered="false"
          lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="multiLinkType" ordered="false"
          lowerBound="1" eType="#//pattern/MultiLinkType" defaultValueLiteral="DIRECT"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="negative" ordered="false"
          lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="sourceLink" ordered="false"
          lowerBound="1" eType="#//pattern/Link" eOpposite="#//pattern/Link/multiLinkFromSource"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="targetObject" ordered="false"
          eType="#//pattern/Object"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="targetLink" ordered="false"
          lowerBound="1" eType="#//pattern/Link" eOpposite="#//pattern/Link/multiLinkToTarget"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="MultiLinkType">
      <eLiterals name="FIRST"/>
      <eLiterals name="LAST" value="1"/>
      <eLiterals name="DIRECT" value="2"/>
      <eLiterals name="INDIRECT" value="3"/>
      <eLiterals name="INDEX" value="4"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ObjectPattern" eSuperTypes="#//CommentableElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="containedObjects" ordered="false"
          upperBound="-1" eType="#//pattern/Object" containment="true" eOpposite="#//pattern/Object/pattern"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="statement" upperBound="-1"
          eType="#//Expression" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="containingNode" ordered="false"
          eType="#//pattern/StoryNode" eOpposite="#//pattern/StoryNode/containedPattern"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="parentPattern" ordered="false"
          eType="#//pattern/ObjectPattern" eOpposite="#//pattern/ObjectPattern/childPattern"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="childPattern" ordered="false"
          upperBound="-1" eType="#//pattern/ObjectPattern" containment="true" eOpposite="#//pattern/ObjectPattern/parentPattern"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="constraint" ordered="false"
          lowerBound="1" eType="#//pattern/Constraint" defaultValueLiteral="NONE"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="constraintExpression"
          ordered="false" upperBound="-1" eType="#//Expression" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="StoryNode" eSuperTypes="#//activities/ActivityNode">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="forEach" ordered="false"
          lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="containedPattern" ordered="false"
          lowerBound="1" eType="#//pattern/ObjectPattern" containment="true" eOpposite="#//pattern/ObjectPattern/containingNode"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Path" eSuperTypes="#//pattern/Link">
      <eStructuralFeatures xsi:type="ecore:EReference" name="pathExpression" ordered="false"
          lowerBound="1" eType="#//Expression" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Object" eSuperTypes="#//TypedElement #//NamedElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="ownedAttributeExpression"
          ordered="false" upperBound="-1" eType="#//pattern/AttributeExpression" containment="true"
          eOpposite="#//pattern/AttributeExpression/owningObject"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="linkToSource" ordered="false"
          upperBound="-1" eType="#//pattern/Link" eOpposite="#//pattern/Link/target"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="linkToTarget" ordered="false"
          upperBound="-1" eType="#//pattern/Link" containment="true" eOpposite="#//pattern/Link/source"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="pattern" ordered="false"
          eType="#//pattern/ObjectPattern" eOpposite="#//pattern/ObjectPattern/containedObjects"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="bound" ordered="false"
          lowerBound="1" eType="#//pattern/BoundType" defaultValueLiteral="UNBOUND"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="constraint" ordered="false"
          lowerBound="1" eType="#//pattern/Constraint" defaultValueLiteral="NONE"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="modifier" ordered="false"
          lowerBound="1" eType="#//pattern/Modifier" defaultValueLiteral="NONE"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="classifier" ordered="false"
          lowerBound="1" eType="ecore:EClass platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EClass"
          volatile="true">
        <eAnnotations source="redefines" references="#//TypedElement/type"/>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EReference" name="bindingExpression" ordered="false"
          eType="#//Expression" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="receivedCollaboration"
          ordered="false" upperBound="-1" eType="#//expressions/Collaboration" eOpposite="#//expressions/Collaboration/target"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="sentCollaboration" ordered="false"
          upperBound="-1" eType="#//expressions/Collaboration" eOpposite="#//expressions/Collaboration/source"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="activities" nsURI="http://ns.storydriven.org/sdm/activities/0.1.0"
      nsPrefix="sdma">
    <eClassifiers xsi:type="ecore:EClass" name="Activity" eSuperTypes="#//CommentableElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="ownedActivityNode" ordered="false"
          upperBound="-1" eType="#//activities/ActivityNode" containment="true" eOpposite="#//activities/ActivityNode/owningActivity"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="owningOperation" ordered="false"
          eType="#//activities/OperationExtension" eOpposite="#//activities/OperationExtension/ownedActivity"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="OperationExtension" eSuperTypes="#//Extension">
      <eStructuralFeatures xsi:type="ecore:EReference" name="ownedActivity" ordered="false"
          eType="#//activities/Activity" containment="true" eOpposite="#//activities/Activity/owningOperation"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ActivityEdge" eSuperTypes="#//ExtendableElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="target" ordered="false"
          lowerBound="1" eType="#//activities/ActivityNode" eOpposite="#//activities/ActivityNode/incoming"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="source" ordered="false"
          lowerBound="1" eType="#//activities/ActivityNode" eOpposite="#//activities/ActivityNode/outgoing"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="guardType" ordered="false"
          lowerBound="1" eType="#//activities/TransitionGuard" defaultValueLiteral="NONE"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="ownedGuardExpression"
          ordered="false" eType="#//Expression" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="TransitionGuard">
      <eLiterals name="NONE"/>
      <eLiterals name="SUCCESS" value="1"/>
      <eLiterals name="FAILURE" value="2"/>
      <eLiterals name="EACH_TIME" value="3"/>
      <eLiterals name="END" value="4"/>
      <eLiterals name="ELSE" value="5"/>
      <eLiterals name="BOOL" value="6"/>
      <eLiterals name="EXCEPTION" value="7"/>
      <eLiterals name="FINALLY" value="8"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="DecisionNode" eSuperTypes="#//activities/ActivityNode"/>
    <eClassifiers xsi:type="ecore:EClass" name="ExceptionExpression" eSuperTypes="#//Expression">
      <eStructuralFeatures xsi:type="ecore:EReference" name="exceptionType" ordered="false"
          upperBound="-1" eType="ecore:EClass platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EClassifier"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="variableName" ordered="false"
          lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="StartNode" eSuperTypes="#//activities/ActivityNode"/>
    <eClassifiers xsi:type="ecore:EClass" name="StatementNode" eSuperTypes="#//activities/ActivityNode">
      <eStructuralFeatures xsi:type="ecore:EReference" name="statementExpression"
          ordered="false" lowerBound="1" eType="#//Expression" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="StopNode" eSuperTypes="#//activities/ActivityNode">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="flowStopOnly" ordered="false"
          lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="returnValue" ordered="false"
          eType="#//Expression" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="StructuredNode" eSuperTypes="#//activities/ActivityNode">
      <eStructuralFeatures xsi:type="ecore:EReference" name="ownedActivityNode" ordered="false"
          upperBound="-1" eType="#//activities/ActivityNode" containment="true" eOpposite="#//activities/ActivityNode/owningActivityNode"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ActivityNode" abstract="true" eSuperTypes="#//CommentableElement #//NamedElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="owningActivity" ordered="false"
          eType="#//activities/Activity" eOpposite="#//activities/Activity/ownedActivityNode"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="incoming" ordered="false"
          upperBound="-1" eType="#//activities/ActivityEdge" eOpposite="#//activities/ActivityEdge/target"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="outgoing" ordered="false"
          upperBound="-1" eType="#//activities/ActivityEdge" containment="true" eOpposite="#//activities/ActivityEdge/source"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="owningActivityNode" ordered="false"
          eType="#//activities/StructuredNode" eOpposite="#//activities/StructuredNode/ownedActivityNode"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="templates" nsURI="http://ns.storydriven.org/sdm/templates/0.1.0"
      nsPrefix="sdmt">
    <eClassifiers xsi:type="ecore:EClass" name="ObjectPatternTemplate" eSuperTypes="#//pattern/ObjectPattern">
      <eStructuralFeatures xsi:type="ecore:EReference" name="typeParameter" ordered="false"
          upperBound="-1" eType="ecore:EClass platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EClassifier"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="templateBinding" ordered="false"
          upperBound="-1" eType="#//templates/TemplateBinding" containment="true"
          eOpposite="#//templates/TemplateBinding/template"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="TemplateBinding" eSuperTypes="#//ExtendableElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="boundParameter" ordered="false"
          lowerBound="1" eType="ecore:EClass platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EClassifier"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="bindingExpression" ordered="false"
          lowerBound="1" eType="#//Expression" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="propertyBinding" ordered="false"
          upperBound="-1" eType="#//templates/PropertyBinding" containment="true"
          eOpposite="#//templates/PropertyBinding/templateBinding"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="template" ordered="false"
          lowerBound="1" eType="#//templates/ObjectPatternTemplate" eOpposite="#//templates/ObjectPatternTemplate/templateBinding"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="PropertyBinding" eSuperTypes="#//ExtendableElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="boundProperty" ordered="false"
          lowerBound="1" eType="ecore:EClass platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EStructuralFeature"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="bindingExpression" ordered="false"
          lowerBound="1" eType="#//Expression" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="templateBinding" ordered="false"
          lowerBound="1" eType="#//templates/TemplateBinding" eOpposite="#//templates/TemplateBinding/propertyBinding"/>
    </eClassifiers>
  </eSubpackages>
</ecore:EPackage>
