<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="modeling"
    nsURI="http://ns.storydriven.org/sdm/0.1.0" nsPrefix="sdm">
  <eClassifiers xsi:type="ecore:EClass" name="Expression" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="TypedElement" abstract="true" eSuperTypes="#//ExtendableElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" ordered="false" eType="ecore:EClass platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EClassifier"
        unsettable="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="genericType" ordered="false"
        eType="ecore:EClass platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EGenericType"
        unsettable="true" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ExtendableElement" abstract="true" eSuperTypes="platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EObject">
    <eOperations name="getExtension" ordered="false" lowerBound="1" eType="#//Extension">
      <eParameters name="type" ordered="false" lowerBound="1" eType="ecore:EClass platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EClass"/>
    </eOperations>
    <eOperations name="provideExtension" ordered="false" lowerBound="1" eType="#//Extension">
      <eParameters name="type" ordered="false" lowerBound="1" eType="ecore:EClass platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EClass"/>
    </eOperations>
    <eOperations name="getAnnotation" ordered="false" lowerBound="1" eType="ecore:EClass platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EAnnotation">
      <eParameters name="source" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eOperations name="provideAnnotation" ordered="false" lowerBound="1" eType="ecore:EClass platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EAnnotation">
      <eParameters name="source" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="annotation" ordered="false"
        upperBound="-1" eType="ecore:EClass platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EAnnotation"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="extension" ordered="false"
        upperBound="-1" eType="#//Extension" containment="true" eOpposite="#//Extension/extendableBase"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Extension" abstract="true" eSuperTypes="#//ExtendableElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="base" ordered="false" lowerBound="1"
        eType="ecore:EClass platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EObject"
        changeable="false" volatile="true" transient="true" derived="true">
      <eAnnotations source="union"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="modelBase" ordered="false"
        eType="ecore:EClass platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EModelElement"
        volatile="true" transient="true" unsettable="true" derived="true">
      <eAnnotations source="subsets" references="#//Extension/base"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="owningAnnotation" ordered="false"
        eType="ecore:EClass platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EAnnotation"
        volatile="true" transient="true" unsettable="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="extendableBase" ordered="false"
        eType="#//ExtendableElement" eOpposite="#//ExtendableElement/extension">
      <eAnnotations source="subsets" references="#//Extension/base"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NamedElement" abstract="true" eSuperTypes="#//ExtendableElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" ordered="false" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CommentableElement" abstract="true"
      eSuperTypes="#//ExtendableElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="comment" ordered="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eSubpackages name="expressions" nsURI="http://ns.storydriven.org/sdm/expressions/0.1.0"
      nsPrefix="sdme">
    <eClassifiers xsi:type="ecore:EEnum" name="LogicOperator">
      <eLiterals name="AND"/>
      <eLiterals name="OR" value="1"/>
      <eLiterals name="XOR" value="2"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="ComparingOperator">
      <eLiterals name="LESS"/>
      <eLiterals name="LESS_OR_EQUAL" value="1" literal=""/>
      <eLiterals name="EQUAL" value="2"/>
      <eLiterals name="GREATER_OR_EQUAL" value="3"/>
      <eLiterals name="GREATER" value="4"/>
      <eLiterals name="UNEQUAL" value="5"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="ArithmeticOperator">
      <eLiterals name="PLUS"/>
      <eLiterals name="MINUS" value="1"/>
      <eLiterals name="TIMES" value="2"/>
      <eLiterals name="DIVIDE" value="3"/>
      <eLiterals name="MODULO" value="4"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="TextualExpression" eSuperTypes="#//Expression">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="expressionText" ordered="false"
          lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="language" ordered="false"
          lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="languageVersion" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="LiteralExpression" eSuperTypes="#//Expression">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="valueType" lowerBound="1"
          eType="ecore:EClass platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EDataType"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="AttributeValueExpression" eSuperTypes="#//Expression">
      <eStructuralFeatures xsi:type="ecore:EReference" name="object" lowerBound="1"
          eType="#//pattern/ObjectVariable"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="attribute" lowerBound="1"
          eType="ecore:EClass platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EAttribute"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ObjectVariableExpression" eSuperTypes="#//Expression">
      <eStructuralFeatures xsi:type="ecore:EReference" name="object" lowerBound="1"
          eType="#//pattern/ObjectVariable"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="BinaryExpression" abstract="true"
        eSuperTypes="#//Expression">
      <eStructuralFeatures xsi:type="ecore:EReference" name="leftExpression" lowerBound="1"
          eType="#//Expression" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="rightExpression" lowerBound="1"
          eType="#//Expression" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="NotExpression" eSuperTypes="#//Expression">
      <eStructuralFeatures xsi:type="ecore:EReference" name="negatedExpression" lowerBound="1"
          eType="#//Expression" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="BinaryLogicExpression" eSuperTypes="#//expressions/BinaryExpression">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="operator" lowerBound="1"
          eType="#//expressions/LogicOperator"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ComparisonExpression" eSuperTypes="#//expressions/BinaryExpression">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="operator" lowerBound="1"
          eType="#//expressions/ComparingOperator"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ArithmeticExpression" eSuperTypes="#//expressions/BinaryExpression">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="operator" lowerBound="1"
          eType="#//expressions/ArithmeticOperator"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="MethodCallExpression" eSuperTypes="#//Expression">
      <eAnnotations>
        <details key="documentation" value="Represents the invocation of a method."/>
      </eAnnotations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="targetObject" eType="#//pattern/ObjectVariable"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="callExpression" lowerBound="1"
          eType="#//Expression"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ExceptionVariableExpression" eSuperTypes="#//Expression">
      <eAnnotations>
        <details key="documentation" value="Represents the Exception variable declared as a transition guard."/>
      </eAnnotations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="exceptionVariable" lowerBound="1"
          eType="#//activities/ExceptionVariable"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ObjectSetSizeExpression" eSuperTypes="#//Expression">
      <eAnnotations>
        <details key="documentation" value="represents the number of elements in a set"/>
      </eAnnotations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="set" lowerBound="1" eType="#//pattern/ObjectSetVariable"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="pattern" nsURI="http://ns.storydriven.org/sdm/pattern/0.1.0"
      nsPrefix="sdmp">
    <eClassifiers xsi:type="ecore:EEnum" name="BindingState">
      <eLiterals name="UNBOUND"/>
      <eLiterals name="BOUND" value="1"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="BindingSemantics">
      <eLiterals name="NONE"/>
      <eLiterals name="NEGATIVE" value="1"/>
      <eLiterals name="OPTIONAL" value="2"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="Modifier">
      <eLiterals name="NONE"/>
      <eLiterals name="CREATE" value="1"/>
      <eLiterals name="DESTROY" value="2"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="OrderConstraintType">
      <eLiterals name="FIRST"/>
      <eLiterals name="LAST" value="1"/>
      <eLiterals name="DIRECT" value="2"/>
      <eLiterals name="INDIRECT" value="3"/>
      <eLiterals name="INDEX" value="4"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="MatchingPattern" eSuperTypes="#//CommentableElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="objectVariable" ordered="false"
          upperBound="-1" eType="#//pattern/ObjectVariable" containment="true" eOpposite="#//pattern/ObjectVariable/pattern"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="linkVariable" upperBound="-1"
          eType="#//pattern/LinkVariable" containment="true" eOpposite="#//pattern/LinkVariable/pattern"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="constraint" ordered="false"
          upperBound="-1" eType="#//pattern/Constraint" containment="true" eOpposite="#//pattern/Constraint/pattern"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="containedPattern" ordered="false"
          upperBound="-1" eType="#//pattern/MatchingPattern" containment="true" eOpposite="#//pattern/MatchingPattern/parentPattern"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="parentPattern" ordered="false"
          eType="#//pattern/MatchingPattern" eOpposite="#//pattern/MatchingPattern/containedPattern"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="bindingType" ordered="false"
          lowerBound="1" eType="#//pattern/BindingSemantics" defaultValueLiteral="NONE"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ObjectVariable" eSuperTypes="#//TypedElement #//NamedElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="pattern" ordered="false"
          lowerBound="1" eType="#//pattern/MatchingPattern" eOpposite="#//pattern/MatchingPattern/objectVariable"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="incomingLink" ordered="false"
          upperBound="-1" eType="#//pattern/LinkVariable" eOpposite="#//pattern/LinkVariable/target"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="outgoingLink" ordered="false"
          upperBound="-1" eType="#//pattern/LinkVariable" eOpposite="#//pattern/LinkVariable/source"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="classifier" ordered="false"
          lowerBound="1" eType="ecore:EClass platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EClass"
          volatile="true">
        <eAnnotations source="redefines" references="#//TypedElement/type"/>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EReference" name="constraint" upperBound="-1"
          eType="#//pattern/Constraint" containment="true" eOpposite="#//pattern/Constraint/objectVariable"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="attributeAssignment"
          upperBound="-1" eType="#//pattern/AttributeAssignment" containment="true"
          eOpposite="#//pattern/AttributeAssignment/objectVariable"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="bindingExpression" ordered="false"
          eType="#//Expression" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="bindingType" ordered="false"
          lowerBound="1" eType="#//pattern/BindingSemantics" defaultValueLiteral="NONE"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="bindingState" lowerBound="1"
          eType="#//pattern/BindingState"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="modifier" lowerBound="1"
          eType="#//pattern/Modifier"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="linkOrderConstraint"
          upperBound="-1" eType="#//pattern/LinkOrderConstraint" containment="true"
          eOpposite="#//pattern/LinkOrderConstraint/referencingObject"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="LinkVariable" eSuperTypes="#//NamedElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="pattern" lowerBound="1"
          eType="#//pattern/MatchingPattern" eOpposite="#//pattern/MatchingPattern/linkVariable"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="target" ordered="false"
          lowerBound="1" eType="#//pattern/ObjectVariable" eOpposite="#//pattern/ObjectVariable/incomingLink"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="source" ordered="false"
          lowerBound="1" eType="#//pattern/ObjectVariable" eOpposite="#//pattern/ObjectVariable/outgoingLink"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="firstLinkOrderConstraint"
          ordered="false" upperBound="-1" eType="#//pattern/LinkOrderConstraint" eOpposite="#//pattern/LinkOrderConstraint/firstLink"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="secondLinkOrderConstraint"
          ordered="false" upperBound="-1" eType="#//pattern/LinkOrderConstraint" eOpposite="#//pattern/LinkOrderConstraint/secondLink"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="sourceEnd" ordered="false"
          lowerBound="1" eType="ecore:EClass platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EReference"
          volatile="true" transient="true" derived="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="targetEnd" ordered="false"
          eType="ecore:EClass platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EReference"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="qualifierExpression"
          ordered="false" eType="#//Expression" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="bindingType" ordered="false"
          lowerBound="1" eType="#//pattern/BindingSemantics" defaultValueLiteral="NONE"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="bindingState" lowerBound="1"
          eType="#//pattern/BindingState"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="modifier" lowerBound="1"
          eType="#//pattern/Modifier"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="LinkOrderConstraint" eSuperTypes="#//ExtendableElement">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="index" ordered="false"
          lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="multiLinkType" ordered="false"
          lowerBound="1" eType="#//pattern/OrderConstraintType" defaultValueLiteral="DIRECT"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="negative" ordered="false"
          lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="secondLink" ordered="false"
          lowerBound="1" eType="#//pattern/LinkVariable" eOpposite="#//pattern/LinkVariable/secondLinkOrderConstraint"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="firstLink" ordered="false"
          lowerBound="1" eType="#//pattern/LinkVariable" eOpposite="#//pattern/LinkVariable/firstLinkOrderConstraint"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="referencingObject" lowerBound="1"
          eType="#//pattern/ObjectVariable" eOpposite="#//pattern/ObjectVariable/linkOrderConstraint"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Path" eSuperTypes="#//pattern/LinkVariable">
      <eStructuralFeatures xsi:type="ecore:EReference" name="ownedPathExpression"
          ordered="false" lowerBound="1" eType="#//Expression" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="AttributeAssignment">
      <eStructuralFeatures xsi:type="ecore:EReference" name="objectVariable" lowerBound="1"
          eType="#//pattern/ObjectVariable" eOpposite="#//pattern/ObjectVariable/attributeAssignment"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="ownedValueExpression"
          lowerBound="1" eType="#//Expression" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="attribute" lowerBound="1"
          eType="ecore:EClass platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EAttribute"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Constraint">
      <eStructuralFeatures xsi:type="ecore:EReference" name="constraintExpression"
          lowerBound="1" eType="#//Expression" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="pattern" eType="#//pattern/MatchingPattern"
          eOpposite="#//pattern/MatchingPattern/constraint"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="objectVariable" eType="#//pattern/ObjectVariable"
          eOpposite="#//pattern/ObjectVariable/constraint"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="StoryPattern" eSuperTypes="#//pattern/MatchingPattern"/>
    <eClassifiers xsi:type="ecore:EClass" name="ObjectSetVariable" eSuperTypes="#//pattern/ObjectVariable"/>
  </eSubpackages>
  <eSubpackages name="activities" nsURI="http://ns.storydriven.org/sdm/activities/0.1.0"
      nsPrefix="sdma">
    <eClassifiers xsi:type="ecore:EEnum" name="TransitionGuard">
      <eLiterals name="NONE"/>
      <eLiterals name="SUCCESS" value="1"/>
      <eLiterals name="FAILURE" value="2"/>
      <eLiterals name="EACH_TIME" value="3"/>
      <eLiterals name="END" value="4"/>
      <eLiterals name="ELSE" value="5"/>
      <eLiterals name="BOOL" value="6"/>
      <eLiterals name="EXCEPTION" value="7"/>
      <eLiterals name="FINALLY" value="8"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="OperationExtension" eSuperTypes="#//Extension #//calls/Callable">
      <eStructuralFeatures xsi:type="ecore:EReference" name="ownedActivity" ordered="false"
          eType="#//activities/Activity" containment="true" eOpposite="#//activities/Activity/owningOperation"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="operation" eType="ecore:EClass platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EOperation"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Activity" eSuperTypes="#//CommentableElement #//calls/Callable">
      <eStructuralFeatures xsi:type="ecore:EReference" name="ownedActivityNode" ordered="false"
          upperBound="-1" eType="#//activities/ActivityNode" containment="true" eOpposite="#//activities/ActivityNode/owningActivity"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="ownedActivityEdge" upperBound="-1"
          eType="#//activities/ActivityEdge" containment="true" eOpposite="#//activities/ActivityEdge/owningActivity"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="owningOperation" ordered="false"
          eType="#//activities/OperationExtension" eOpposite="#//activities/OperationExtension/ownedActivity"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="precondition" eType="#//activities/StoryNode">
        <eAnnotations>
          <details key="documentation" value="References a story node which represents the precondition for the execution of the activity. I.e., the activity is executed, iff the object structure in the story node can be matched. Obviously the referenced story node may only contain black (i.e., non-create and non-destroy) objects and links."/>
        </eAnnotations>
      </eStructuralFeatures>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ActivityNode" abstract="true" eSuperTypes="#//CommentableElement #//NamedElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="owningActivity" ordered="false"
          eType="#//activities/Activity" eOpposite="#//activities/Activity/ownedActivityNode"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="incoming" ordered="false"
          upperBound="-1" eType="#//activities/ActivityEdge" eOpposite="#//activities/ActivityEdge/target"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="outgoing" ordered="false"
          upperBound="-1" eType="#//activities/ActivityEdge" eOpposite="#//activities/ActivityEdge/source"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="owningActivityNode" ordered="false"
          eType="#//activities/StructuredNode" eOpposite="#//activities/StructuredNode/ownedActivityNode"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ActivityEdge" eSuperTypes="#//ExtendableElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="owningActivity" lowerBound="1"
          eType="#//activities/Activity" eOpposite="#//activities/Activity/ownedActivityEdge"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="target" ordered="false"
          lowerBound="1" eType="#//activities/ActivityNode" eOpposite="#//activities/ActivityNode/incoming"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="source" ordered="false"
          lowerBound="1" eType="#//activities/ActivityNode" eOpposite="#//activities/ActivityNode/outgoing"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="guardType" ordered="false"
          lowerBound="1" eType="#//activities/TransitionGuard" defaultValueLiteral="NONE"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="guardExpression" ordered="false"
          eType="#//Expression" containment="true">
        <eAnnotations>
          <details key="documentation" value="Points to the boolean expression in case of boolean transition guard."/>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EReference" name="guardException" upperBound="-1"
          eType="#//activities/ExceptionVariable" containment="true" eOpposite="#//activities/ExceptionVariable/activityEdge">
        <eAnnotations>
          <details key="documentation" value="Declares variables representing the Exceptions that lead to firing this transition."/>
        </eAnnotations>
      </eStructuralFeatures>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="StoryNode" abstract="true" eSuperTypes="#//activities/ActivityNode">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="forEach" ordered="false"
          lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="JunctionNode" eSuperTypes="#//activities/ActivityNode"/>
    <eClassifiers xsi:type="ecore:EClass" name="StartNode" eSuperTypes="#//activities/ActivityNode"/>
    <eClassifiers xsi:type="ecore:EClass" name="StopNode" eSuperTypes="#//activities/ActivityNode">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="flowStopOnly" ordered="false"
          lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
        <eAnnotations>
          <details key="documentation" value="true if subactivity is stopped, but not the whole control flow"/>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EReference" name="returnValue" ordered="false"
          eType="#//Expression" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ActivityCallNode" eSuperTypes="#//activities/ActivityNode #//calls/Invocation">
      <eAnnotations>
        <details key="documentation" value="The TransformationCallNode is a special ActivityNode which represents the calling of another story diagram within an activity.&#xD;&#xA;To support polymorphic dispatching, multiple activities can be assigned to it (all of which must have the same call signature, i.e. matching in and out parameters). All assigned activities are then called in the given order and the first one whose precondition is fulfilled is executed (Chain of Responsibilty)."/>
      </eAnnotations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="callee" lowerBound="1"
          upperBound="-1" eType="#//activities/Activity">
        <eAnnotations>
          <details key="documentation" value="References all activities that are to be considered for the polymorphic dispatching of the call. All activities must have the same call signature."/>
        </eAnnotations>
      </eStructuralFeatures>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="StatementNode" eSuperTypes="#//activities/ActivityNode">
      <eStructuralFeatures xsi:type="ecore:EReference" name="statementExpression"
          ordered="false" lowerBound="1" eType="#//Expression" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="StructuredNode" eSuperTypes="#//activities/ActivityNode">
      <eStructuralFeatures xsi:type="ecore:EReference" name="ownedActivityNode" ordered="false"
          upperBound="-1" eType="#//activities/ActivityNode" containment="true" eOpposite="#//activities/ActivityNode/owningActivityNode"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="MatchingStoryNode" eSuperTypes="#//activities/StoryNode">
      <eStructuralFeatures xsi:type="ecore:EReference" name="ownedPattern" ordered="false"
          lowerBound="1" eType="#//pattern/MatchingPattern" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ModifyingStoryNode" eSuperTypes="#//activities/StoryNode">
      <eStructuralFeatures xsi:type="ecore:EReference" name="ownedRule" lowerBound="1"
          eType="#//pattern/StoryPattern" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ExceptionVariable">
      <eAnnotations>
        <details key="documentation" value="Declares a variable representing an Exception that leads to firing a transition (ActivityEdge)."/>
      </eAnnotations>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="variableName" ordered="false"
          lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="exceptionType" ordered="false"
          upperBound="-1" eType="ecore:EClass platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EClass"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="activityEdge" lowerBound="1"
          eType="#//activities/ActivityEdge" eOpposite="#//activities/ActivityEdge/guardException"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="templates" nsURI="http://ns.storydriven.org/sdm/templates/0.1.0"
      nsPrefix="sdmt">
    <eClassifiers xsi:type="ecore:EClass" name="ObjectPatternTemplate" eSuperTypes="#//pattern/MatchingPattern">
      <eStructuralFeatures xsi:type="ecore:EReference" name="typeParameter" ordered="false"
          upperBound="-1" eType="ecore:EClass platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EClassifier"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="templateBinding" ordered="false"
          upperBound="-1" eType="#//templates/TemplateBinding" containment="true"
          eOpposite="#//templates/TemplateBinding/template"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="TemplateBinding" eSuperTypes="#//ExtendableElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="boundParameter" ordered="false"
          lowerBound="1" eType="ecore:EClass platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EClassifier"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="bindingExpression" ordered="false"
          lowerBound="1" eType="#//Expression" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="propertyBinding" ordered="false"
          upperBound="-1" eType="#//templates/PropertyBinding" containment="true"
          eOpposite="#//templates/PropertyBinding/templateBinding"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="template" ordered="false"
          lowerBound="1" eType="#//templates/ObjectPatternTemplate" eOpposite="#//templates/ObjectPatternTemplate/templateBinding"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="PropertyBinding" eSuperTypes="#//ExtendableElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="boundProperty" ordered="false"
          lowerBound="1" eType="ecore:EClass platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EStructuralFeature"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="bindingExpression" ordered="false"
          lowerBound="1" eType="#//Expression" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="templateBinding" ordered="false"
          lowerBound="1" eType="#//templates/TemplateBinding" eOpposite="#//templates/TemplateBinding/propertyBinding"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="calls" nsURI="http://ns.storydriven.org/sdm/calls/0.1.0" nsPrefix="sdmc">
    <eClassifiers xsi:type="ecore:EClass" name="Invocation" eSuperTypes="#//CommentableElement">
      <eAnnotations>
        <details key="documentation" value="Superclass for invocations of behavior which is specified elsewhere, e.g. in methods (MethodCall) or activities (ActivityCallNode). An invocation has one parameter binding for each parameter (in or out) of the called method/activity."/>
      </eAnnotations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="ownedParameterBindings"
          upperBound="-1" eType="#//calls/ParameterBinding" containment="true" eOpposite="#//calls/ParameterBinding/owningInvocation"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Callable" eSuperTypes="#//CommentableElement">
      <eAnnotations>
        <details key="documentation" value="An entity which can be called by an Invocation.&#xD;&#xA;A Callable can have a number of (ordered) parameters which are either in or out parameters. In the case of activities, the number of in and out parameters is unbounded, whereas OperationExtensions can only have one out parameter."/>
      </eAnnotations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="inParameters" upperBound="-1"
          eType="#//calls/Parameter" containment="true" eOpposite="#//calls/Parameter/inParameterOwner"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="outParameters" upperBound="-1"
          eType="#//calls/Parameter" containment="true" eOpposite="#//calls/Parameter/outParameterOwner"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Parameter" eSuperTypes="#//NamedElement">
      <eAnnotations>
        <details key="documentation" value="A parameter defined by a Callable. Can either be an in or out parameter, signified by the corresponding reference to the owning Callable (only one of those references can be assigned at any time).&#xD;&#xA;A parameter is typed by an EClassifier."/>
      </eAnnotations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1"
          eType="ecore:EClass platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EClassifier"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="inParameterOwner" lowerBound="1"
          eType="#//calls/Callable" eOpposite="#//calls/Callable/inParameters"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="outParameterOwner" eType="#//calls/Callable"
          eOpposite="#//calls/Callable/outParameters"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ParameterBinding" eSuperTypes="#//CommentableElement">
      <eAnnotations>
        <details key="documentation" value="Binds a parameter to a certain value for a given invocation. The value of the parameter is represented by an expression."/>
      </eAnnotations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="owningInvocation" lowerBound="1"
          eType="#//calls/Invocation" eOpposite="#//calls/Invocation/ownedParameterBindings"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="ownedValueExpression"
          lowerBound="1" eType="#//Expression" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="parameter" lowerBound="1"
          eType="#//calls/Parameter"/>
    </eClassifiers>
  </eSubpackages>
</ecore:EPackage>
