/*
* generated by Xtext
*/
package org.storydriven.storydiagrams.expressions.ui.contentassist;

/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class PathExpressionsProposalProvider extends AbstractPathExpressionsProposalProvider {

}
