/*
 * generated by Xtext
 */
package org.storydriven.storydiagrams.expressions.common;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class ExpressionsRuntimeModule extends org.storydriven.storydiagrams.expressions.common.AbstractExpressionsRuntimeModule {

}
