/*
* generated by Xtext
*/
package org.storydriven.storydiagrams.expressions.parser.antlr;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.storydriven.storydiagrams.expressions.services.PathExpressionsGrammarAccess;

import com.google.inject.Inject;

public class PathExpressionsParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private PathExpressionsGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected org.storydriven.storydiagrams.expressions.parser.antlr.internal.InternalPathExpressionsParser createParser(XtextTokenStream stream) {
		return new org.storydriven.storydiagrams.expressions.parser.antlr.internal.InternalPathExpressionsParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "PathExpression";
	}
	
	public PathExpressionsGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(PathExpressionsGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
