/*
* generated by Xtext
*/
package org.storydriven.storydiagrams.expressions.common.ui.contentassist;

/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class ExpressionsProposalProvider extends AbstractExpressionsProposalProvider {

}
